spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: jdbc:h2:mem:demo_app;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: always
  flyway:
    enabled: true
    outOfOrder: true
  jpa:
    show-sql: ${MYSQL_SHOW_SQL:false}

  main:
    banner-mode: "off"
    web-application-type: servlet
    allow-bean-definition-overriding: true
  jackson:
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: never
      cache:
        time-to-live: 20000ms
    info:
      enabled: true

server:
  compression:
    enabled: true
  servlet:
    context-path: /auditable
